# --- Definitions --- #
# URL
baseurl: "/portfolio"

# Name of website
site_title: "s-ikeda portfolio website"
# Author name
author: "s-ikeda"

# GitHub
github_url: "https://github.com/s-ike/"


# --- Settings --- #
sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

plugins:
  - jekyll-postcss

include: ["node_modules/tailwindcss"]
