site_title: "s-ikeda portfolio website"
github_url: "https://github.com/s-ike/"
baseurl: "/portfolio"

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

plugins:
  - jekyll-postcss

include: ["node_modules/tailwindcss"]
